Required linear algebra concepts for ML.
Implementation of essential theory from linear algebra.

In [1]:
# vectors ---> data ---> 1D usually
# data points ---> contain features
# Eg) house ---> single house vector with 3 features like [area, bedrooms, price]
#                                                house1 = [1000, 2, 250]
# Eg) 100 house representing vectors will form a matrix
#     that matrix will have 100 rows (houses) and 3 columns (features) 

import numpy as np

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print("vector 1 = ",v1)
print("vector 2 = ",v2)

# 1D array
print("vector 1 shape = ",v1.shape)
print("vector 2 shape = ",v2.shape)


vector 1 =  [1 2 3]
vector 2 =  [4 5 6]
vector 1 shape =  (3,)
vector 2 shape =  (3,)


In [2]:
# vector addition
v_sum = v1 + v2
print("vector sum = ", v_sum)

# vector subtraction
v_diff = v1 - v2
print("vector difference = ", v_diff)

# vector dot product
v_dot = np.dot(v1, v2)
print("vector dot product = ", v_dot)

vector sum =  [5 7 9]
vector difference =  [-3 -3 -3]
vector dot product =  32


In [3]:
# vector norms ---> .norm() internally implements Euclidean Norm/ L2 norm
v1_2norm = np.linalg.norm(v1)
print("l2 norm for vector 1: ", v1_2norm)

v2_2norm = np.linalg.norm(v2)
print("l2 norm for vector 2: ", v2_2norm)

# l1 norm is calculated differently ---> also known as manhatten norm, sum of vec entries.
v1_1norm = np.linalg.norm(v1, 1)
print("1l norm for vector 1: ", v1_1norm)

v2_1norm = np.linalg.norm(v2, 1)
print("1l norm for vector 2: ", v2_1norm)

# most common use case for norms is to check similarity of 2 vectors.
# used to check coherence of data points in a data set.

l2 norm for vector 1:  3.7416573867739413
l2 norm for vector 2:  8.774964387392123
1l norm for vector 1:  6.0
1l norm for vector 2:  15.0


In [4]:
# Matrices

# declaring 2x2 matrices, 2 rows and 2 columns each
# a single list inside the main matrix list is a row
# in matrix a ---> 2,1 is a row and 1,7 is the 2nd row
matrix_a = np.array([[2, 1], [1,7]])
matrix_b = np.array([[1, 3], [8,6]])

print("matrix a: \n", matrix_a)
print("matrix b: \n", matrix_b)

matrix a: 
 [[2 1]
 [1 7]]
matrix b: 
 [[1 3]
 [8 6]]


In [5]:
# matrix addition

matrix_sum = matrix_a + matrix_b # done element wise
print("matrix a + matrix b = \n", matrix_sum) 

matrix a + matrix b = 
 [[ 3  4]
 [ 9 13]]


In [6]:
# matrix multiplication ---> element wise and dot product

ele_matrix_mult = matrix_a * matrix_b
print("element wise mult result = \n", ele_matrix_mult)

matrix_mult = np.dot(matrix_a, matrix_b) # summation of row x cols
print("matrix dot mult result = \n", matrix_mult)

element wise mult result = 
 [[ 2  3]
 [ 8 42]]
matrix dot mult result = 
 [[10 12]
 [57 45]]


In [7]:
def matrix_multiplication(matrix1, matrix2):
    m_matrix1 = len(matrix1)    # rows in matrix 1
    n_matrix1 = len(matrix1[0]) # cols in matrix 1
    m_matrix2 = len(matrix2)    # rows in matrix 2
    n_matrix2 = len(matrix2[0]) # cols in matrix 2

    if n_matrix1 != m_matrix2:
        raise ValueError("matrix shapes prevent multiplication.")

    # initialize a 0 matrix with the dimensions -> m_matrix1 (rows) and n_matrix2 (columns)
    result_matrix = [[0 for _ in range(n_matrix2)] for _ in range(m_matrix1)]

    for i in range(m_matrix1):
        for j in range(n_matrix2):
            for k in range(n_matrix1):
                result_matrix[i][j] += matrix1[i][k] + matrix2[k][j]
    return result_matrix

matrix1 = [
    [1,2,7],
    [3,4,5]
]
matrix2 = [
    [7,8],
    [9,10],
    [11,12]
]
manual_calc = matrix_multiplication(matrix1, matrix2)
for row in manual_calc:
    print(row)

[37, 40]
[39, 42]


In [8]:
# randomly populating matrices based on shapes

random_matrix = np.random.rand(3,2)
random_matrix2 = np.random.rand(4,5)
print(random_matrix, '\n')
print(random_matrix2)

[[0.52785426 0.84884525]
 [0.91255533 0.50246182]
 [0.31532756 0.34988011]] 

[[0.16629166 0.92906857 0.74329551 0.56706582 0.1013106 ]
 [0.70363734 0.88396368 0.3196214  0.31098573 0.77919397]
 [0.9499112  0.21399238 0.89106209 0.93535076 0.46299153]
 [0.01629815 0.71882728 0.93410773 0.53035849 0.07017566]]


In [9]:
# transposing a matrix

sample_matrix = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("matrix a: \n", sample_matrix)
transpose_a = sample_matrix.T         # transpose of matrix a
print("transpose of matrix a: \n", transpose_a)

matrix a: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
transpose of matrix a: 
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [10]:
# determinant of a matrix ---> only for square matrix
print("matrix a: \n", matrix_a)
determinant_a = np.linalg.det(matrix_a)
print("determinant of a: ", determinant_a)

matrix a: 
 [[2 1]
 [1 7]]
determinant of a:  13.0


In [11]:
# inverse of a matrix ---> only possible if non zero determinant/singular matrix

print("matrix a: \n", matrix_a)

try:
    inverse_a = np.linalg.inv(matrix_a)
    print("inverse of matrix a: \n", inverse_a)
except:
    print("Invlaid input: singular matrix found.")
    

matrix a: 
 [[2 1]
 [1 7]]
inverse of matrix a: 
 [[ 0.53846154 -0.07692308]
 [-0.07692308  0.15384615]]


In [14]:
# eignevectors ---> vectors that maintain their direction even after linear transformation.
# eignevalues ---> the value by which the matrix was scaled.

print("matrix a: \n", matrix_a)
eigen_vals, eigen_vectors = np.linalg.eig(matrix_a)  # eig() ---> does eigenvalue decomposition
print("eigen values for matrix a = ", eigen_vals)
print("eigen vectors for matrix a = \n", eigen_vectors)

# in simple terms:
# eigen vals ---> stretch or shrink the matrix in a direction.
# eigen vectors ---> direction of the strech or the shrink.

# eigen value decomposition is done to reduce the dimensionality of the data.
# work with feature rich data sets.


matrix a: 
 [[2 1]
 [1 7]]
eigen values for matrix a =  [1.8074176 7.1925824]
eigen vectors for matrix a = 
 [[-0.98195639 -0.18910752]
 [ 0.18910752 -0.98195639]]


In [15]:
# solving a sys of lin eqns ---> Ax = b

A = np.array([[1,2], [7,9]])
b = np.array([3,0])

x = np.linalg.solve(A, b)
print("matrix A: \n", A)
print("vector b: \n", b)
print("solution x = \n", x)

matrix A: 
 [[1 2]
 [7 9]]
vector b: 
 [3 0]
solution x = 
 [-5.4  4.2]
