Required linear algebra concepts for ML.
Implementation of essential theory from linear algebra.

In [2]:
# vectors ---> data ---> 1D usually
# data points ---> contain features
# Eg) house ---> single house vector with 3 features like [area, bedrooms, price]
#                                                house1 = [1000, 2, 250]
# Eg) 100 house representing vectors will form a matrix
#     that matrix will have 100 rows (houses) and 3 columns (features) 

import numpy as np

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print("vector 1 = ",v1)
print("vector 2 = ",v2)

# 1D array
print("vector 1 shape = ",v1.shape)
print("vector 2 shape = ",v2.shape)


vector 1 =  [1 2 3]
vector 2 =  [4 5 6]
vector 1 shape =  (3,)
vector 2 shape =  (3,)


In [3]:
# vector addition
v_sum = v1 + v2
print("vector sum = ", v_sum)

# vector subtraction
v_diff = v1 - v2
print("vector difference = ", v_diff)

# vector dot product
v_dot = np.dot(v1, v2)
print("vector dot product = ", v_dot)

vector sum =  [5 7 9]
vector difference =  [-3 -3 -3]
vector dot product =  32


In [4]:
# vector norms ---> .norm() internally implements Euclidean Norm/ L2 norm
v1_2norm = np.linalg.norm(v1)
print("l2 norm for vector 1: ", v1_2norm)

v2_2norm = np.linalg.norm(v2)
print("l2 norm for vector 2: ", v2_2norm)

# l1 norm is calculated differently ---> also known as manhatten norm, sum of vec entries.
v1_1norm = np.linalg.norm(v1, 1)
print("1l norm for vector 1: ", v1_1norm)

v2_1norm = np.linalg.norm(v2, 1)
print("1l norm for vector 2: ", v2_1norm)

# most common use case for norms is to check similarity of 2 vectors.
# used to check coherence of data points in a data set.

l2 norm for vector 1:  3.7416573867739413
l2 norm for vector 2:  8.774964387392123
1l norm for vector 1:  6.0
1l norm for vector 2:  15.0


In [5]:
# Matrices

# declaring 2x2 matrices, 2 rows and 2 columns each
# a single list inside the main matrix list is a row
# in matrix a ---> 2,1 is a row and 1,7 is the 2nd row
matrix_a = np.array([[2, 1], [1,7]])
matrix_b = np.array([[1, 3], [8,6]])

print("matrix a: \n", matrix_a)
print("matrix b: \n", matrix_b)

matrix a: 
 [[2 1]
 [1 7]]
matrix b: 
 [[1 3]
 [8 6]]


In [6]:
# matrix addition

matrix_sum = matrix_a + matrix_b # done element wise
print("matrix a + matrix b = \n", matrix_sum) 

matrix a + matrix b = 
 [[ 3  4]
 [ 9 13]]


In [11]:
# matrix multiplication ---> element wise and dot product

ele_matrix_mult = matrix_a * matrix_b
print("element wise mult result = \n", ele_matrix_mult)

matrix_mult = np.dot(matrix_a, matrix_b) # summation of row x cols
print("matrix dot mult result = \n", matrix_mult)

element wise mult result = 
 [[ 2  3]
 [ 8 42]]
matrix dot mult result = 
 [[10 12]
 [57 45]]


In [18]:
def matrix_multiplication(matrix1, matrix2):
    m_matrix1 = len(matrix1)    # rows in matrix 1
    n_matrix1 = len(matrix1[0]) # cols in matrix 1
    m_matrix2 = len(matrix2)    # rows in matrix 2
    n_matrix2 = len(matrix2[0]) # cols in matrix 2

    if n_matrix1 != m_matrix2:
        raise ValueError("matrix shapes prevent multiplication.")

    # initialize a 0 matrix with the dimensions -> m_matrix1 (rows) and n_matrix2 (columns)
    result_matrix = [[0 for _ in range(n_matrix2)] for _ in range(m_matrix1)]

    for i in range(m_matrix1):
        for j in range(n_matrix2):
            for k in range(n_matrix1):
                result_matrix[i][j] += matrix1[i][k] + matrix2[k][j]
    return result_matrix

matrix1 = [
    [1,2,7],
    [3,4,5]
]
matrix2 = [
    [7,8],
    [9,10],
    [11,12]
]
manual_calc = matrix_multiplication(matrix1, matrix2)
for row in manual_calc:
    print(row)

[np.int64(12), np.int64(12)]
[np.int64(17), np.int64(17)]
