Required linear algebra concepts for ML.
Implementation of essential theory from linear algebra.

In [11]:
# vectors ---> data ---> 1D usually
# data points ---> contain features
# Eg) house ---> single house vector with 3 features like [area, bedrooms, price]
#                                                house1 = [1000, 2, 250]
# Eg) 100 house representing vectors will form a matrix
#     that matrix will have 100 rows (houses) and 3 columns (features) 

import numpy as np

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print("vector 1 = ",v1)
print("vector 2 = ",v2)

# 1D array
print("vector 1 shape = ",v1.shape)
print("vector 2 shape = ",v2.shape)


vector 1 =  [1 2 3]
vector 2 =  [4 5 6]
vector 1 shape =  (3,)
vector 2 shape =  (3,)


In [14]:
# vector addition
v_sum = v1 + v2
print("vector sum = ", v_sum)

# vector subtraction
v_diff = v1 - v2
print("vector difference = ", v_diff)

# vector dot product
v_dot = np.dot(v1, v2)
print("vector dot product = ", v_dot)

vector sum =  [5 7 9]
vector difference =  [-3 -3 -3]
vector dot product =  32


In [21]:
# vector norms ---> .norm() internally implements Euclidean Norm/ L2 norm
v1_2norm = np.linalg.norm(v1)
print("l2 norm for vector 1: ", v1_2norm)

v2_2norm = np.linalg.norm(v2)
print("l2 norm for vector 2: ", v2_2norm)

# l1 norm is calculated differently ---> also known as manhatten norm, sum of vec entries.
v1_1norm = np.linalg.norm(v1, 1)
print("1l norm for vector 1: ", v1_1norm)

v2_1norm = np.linalg.norm(v2, 1)
print("1l norm for vector 2: ", v2_1norm)

# most common use case for norms is to check similarity of 2 vectors.
# used to check coherence of data points in a data set.

l2 norm for vector 1:  3.7416573867739413
l2 norm for vector 2:  8.774964387392123
1l norm for vector 1:  6.0
1l norm for vector 2:  15.0


In [23]:
# Matrices

# declaring 2x2 matrices, 2 rows and 2 columns each
# a single list inside the main matrix list is a row
# in matrix a ---> 2,1 is a row and 1,7 is the 2nd row
matrix_a = np.array([[2, 1], [1,7]])
matrix_b = np.array([[1, 3], [8,6]])

print("matrix a: \n", matrix_a)
print("matrix b: \n", matrix_b)

matrix a: 
 [[2 1]
 [1 7]]
matrix b: 
 [[1 3]
 [8 6]]


In [24]:
# matrix addition

matrix_sum = matrix_a + matrix_b # done element wise
print("matrix a + matrix b = \n", matrix_sum) 

matrix a + matrix b = 
 [[ 3  4]
 [ 9 13]]
